version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: skinvestigatorai:0.0.4
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "6543:6543"
      - "6006:6006"
    command: ["pserve", "development.ini", "--reload"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
