version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lesnet:0.1.5
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "6543:6543"
      - "6006:6006"
    command: ["pserve", "development.ini", "--reload"]
