version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: skinvestigatorai:2.0.0
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "6543:6543"
      - "6006:6006"
    command: [ "sh", "train.sh" ]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, utility ]

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1